services:
  fe-dev:
    build:
      context: ./fe
      target: ${PROFILE:-dev}
    volumes:
      - ./fe/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
    depends_on:
      - be-dev
  fe-prod:
    build:
      context: ./fe
      target: ${PROFILE:-prod}
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - 80:80
    env_file:
      - .env
    profiles:
      - prod

  be-dev:
    build:
      context: ./be
      target: ${PROFILE:-dev}
    ports:
      - 3000:3000
    volumes:
      - ./be/src:/app/src
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
  be-prod:
    build:
      context: ./be
      target: ${PROFILE:-prod}
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - app-network
    profiles:
      - prod

networks:
  app-network:
    driver: bridge
