services:
  fe-dev:
    build:
      context: ./fe
      target: ${PROFILE:-dev}
    volumes:
      - ./fe/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
  fe-prod:
    build:
      context: ./fe
      target: ${PROFILE:-prod}
    ports:
      - 80:80
    profiles:
      - prod
